### ISSUE TITLE
[PE-D][Tester B] Inappropriate bolded text.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-F13-1/tp#192]
It doesn't seem appropriate to bold a single word in the user guide

![image.png](https://raw.githubusercontent.com/kimshitong/ped/main/files/4ec7f456-95b8-4696-804d-dbf602d2ed58.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: kimshitong/ped#2

**Comment by xavierpok** [comment]
Intentional stylisation, to discuss during meeting.

**Comment by xavierpok** [comment]
Suggest : Connexion (regular), stylised as **C**onnexion
