### ISSUE TITLE
[PE-D][Tester B] Accepts Invalid Email Input 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-F13-1/tp#194]
It is not possible to have an email address like "aikenduit@hotmail" without a valid top-level domain (TLD) like ".com," ".net," or ".org." An email address without a TLD is considered incomplete and would not work as a valid email address. In the case of "aikenduit@hotmail," it lacks the TLD and would not be a functional email address.

![image.png](https://raw.githubusercontent.com/kimshitong/ped/main/files/d908ba0b-d7de-494c-a5d9-65f776b91dd2.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kimshitong/ped#3

**Comment by xavierpok** [comment]
Note to team : _Theoretically_ possible to have an email w/o a TLD,. though highly discouraged. Can pull sources and add to UG if needed.
