### ISSUE TITLE
[PE-D][Tester D] Entries can contain invalid emails

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-F13-1/tp#200]
New entries added accepts invalid emails as input

![image.png](https://raw.githubusercontent.com/tyouwei/ped/main/files/a312ecab-5dad-4618-85e0-05689d60bdd2.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tyouwei/ped#1

**Comment by xavierpok** [comment]
Other issue covers this. #194. Closing duplicate.
