### ISSUE TITLE
[PE-D][Tester B] Doesn't support long name text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-F13-1/tp#205]
This will be inconvenient for long name people :(, will be better if mentioned in userguide or make a break line for this issue

![image.png](https://raw.githubusercontent.com/kimshitong/ped/main/files/161c6cc4-ce04-4a10-80fa-a6b18494dd7b.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kimshitong/ped#7

**Comment by xavierpok** [comment]
Consider workarounds for very very long names
